name = "Gen2DAgentMotion"
uuid = "1544a2c3-e4ed-46f4-bd66-0c6b390abd0d"
authors = ["Marco Cusumano-Towner <imarcoam@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
